"""Add Call metadata and CallDocument model

Revision ID: ab50dfe9e023
Revises: cbc7783e105e
Create Date: 2026-03-10 11:27:39.813503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab50dfe9e023'
down_revision: Union[str, Sequence[str], None] = 'cbc7783e105e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_source_of_truth', sa.Boolean(), nullable=True),
    sa.Column('stored_path', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extracted_text_length', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_documents_id'), 'call_documents', ['id'], unique=False)
    op.add_column('calls', sa.Column('title_uk', sa.String(), nullable=True))
    op.add_column('calls', sa.Column('title_en', sa.String(), nullable=True))
    op.add_column('calls', sa.Column('applications_received_count', sa.Integer(), nullable=True))
    op.add_column('calls', sa.Column('applications_expected_count', sa.Integer(), nullable=True))
    op.add_column('calls', sa.Column('preliminary_evaluation_capacity', sa.Integer(), nullable=True))
    op.add_column('calls', sa.Column('formal_check_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('calls', sa.Column('preliminary_evaluation_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('calls', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'status')
    op.drop_column('calls', 'preliminary_evaluation_deadline')
    op.drop_column('calls', 'formal_check_deadline')
    op.drop_column('calls', 'preliminary_evaluation_capacity')
    op.drop_column('calls', 'applications_expected_count')
    op.drop_column('calls', 'applications_received_count')
    op.drop_column('calls', 'title_en')
    op.drop_column('calls', 'title_uk')
    op.drop_index(op.f('ix_call_documents_id'), table_name='call_documents')
    op.drop_table('call_documents')
    # ### end Alembic commands ###
