"""Add full text and metadata to SubmittedFile

Revision ID: cbc7783e105e
Revises: 5b369b85300e
Create Date: 2026-03-10 10:53:55.033834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc7783e105e'
down_revision: Union[str, Sequence[str], None] = '5b369b85300e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submitted_files', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('submitted_files', sa.Column('extracted_text_length', sa.Integer(), nullable=True))
    op.add_column('submitted_files', sa.Column('detected_project_registration_number', sa.String(), nullable=True))
    op.add_column('submitted_files', sa.Column('detected_call_title', sa.String(), nullable=True))
    op.add_column('submitted_files', sa.Column('detected_project_title', sa.String(), nullable=True))
    op.add_column('submitted_files', sa.Column('detected_language_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submitted_files', 'detected_language_note')
    op.drop_column('submitted_files', 'detected_project_title')
    op.drop_column('submitted_files', 'detected_call_title')
    op.drop_column('submitted_files', 'detected_project_registration_number')
    op.drop_column('submitted_files', 'extracted_text_length')
    op.drop_column('submitted_files', 'extracted_text')
    # ### end Alembic commands ###
