"""Add call-specific rule fields

Revision ID: dc135f8e1a58
Revises: ab50dfe9e023
Create Date: 2026-03-10 11:53:09.962933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc135f8e1a58'
down_revision: Union[str, Sequence[str], None] = 'ab50dfe9e023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('severity', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_document_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_section', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key('fk_checklist_items_source_document_id', 'call_documents', ['source_document_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_checklist_items_source_document_id', type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('source_section')
        batch_op.drop_column('source_document_id')
        batch_op.drop_column('severity')

    # ### end Alembic commands ###
