"""Add passage and evidence fields to ReportFinding

Revision ID: f4b28d40f07f
Revises: dc135f8e1a58
Create Date: 2026-03-10 14:02:52.691665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b28d40f07f'
down_revision: Union[str, Sequence[str], None] = 'dc135f8e1a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_findings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_evidence', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('source_document_title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_section', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_passage', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_findings', schema=None) as batch_op:
        batch_op.drop_column('source_passage')
        batch_op.drop_column('source_section')
        batch_op.drop_column('source_document_title')
        batch_op.drop_column('package_evidence')

    # ### end Alembic commands ###
